// App shell: header, main navigation (PRD Section 11), footer.
// Responsive layout is handled in index.css.
import MobileNav from './MobileNav.jsx'
import Icon from './Icon.jsx'

const NAV_ITEMS = [
  { label: 'Dashboard', icon: 'dashboard' },
  { label: 'Products', icon: 'products' },
  { label: 'Transactions', icon: 'transactions' },
  { label: 'Alerts', icon: 'alerts' },
  { label: 'Investigations', icon: 'investigations' },
  { label: 'AI Assistant', icon: 'ai' },
  { label: 'Settings', icon: 'settings' },
]

const PAGE_DESCRIPTIONS = {
  Dashboard: 'A clear view of recorded business activity and items to review.',
  Products: 'Manage products and review recorded stock levels.',
  Transactions: 'Record and review activity across your business.',
  Alerts: 'Review signals generated by your configured monitoring rules.',
  Investigations: 'Document evidence, findings, and resolutions.',
  'AI Assistant': 'Explore authorized records with human-review safeguards.',
  Settings: 'Manage your business, team, rules and subscription',
  Notifications: 'See alerts and investigation activity that may need attention.',
}

function Layout({ currentPage, onNavigate, businessName, notificationCount, onOpenNotifications, user, onLogout, children }) {
  return (
    <div className="app shell">
      <aside className="sidebar">
        <div className="brand-block">
          <div className="brand-mark" aria-hidden="true"><Icon name="dashboard" size={22} /></div>
          <div>
            <h1 className="brand">QubWatch</h1>
            <p className="tagline">See what deserves your utmost attention.</p>
          </div>
        </div>

        <nav className="side-nav" aria-label="Main navigation">
          {NAV_ITEMS.map((item) => (
            <button
              key={item.label}
              className={item.label === currentPage ? 'side-nav-btn active' : 'side-nav-btn'}
              onClick={() => onNavigate(item.label)}
            >
              <Icon name={item.icon} size={19} />
              <span>{item.label}</span>
            </button>
          ))}
        </nav>

        <div className="side-controls">
          <div className="sidebar-business">
            <span className="sidebar-business-label">WORKSPACE</span>
            <p className="business-pill">{businessName}</p>
          </div>
          {user && (
            <div className="sidebar-user">
              <span className="user-avatar">{user.name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase()}</span>
              <span className="sidebar-user-copy"><strong>{user.name}</strong><small>{user.role}</small></span>
            </div>
          )}
        </div>
      </aside>

      <div className="shell-main">
        <header className="topbar">
          <div className="topbar-heading">
            <span className="topbar-kicker">BUSINESS MONITORING & INVESTIGATION</span>
            <h2>{currentPage}</h2>
            <p>{PAGE_DESCRIPTIONS[currentPage] || 'Business monitoring and investigation workspace.'}</p>
          </div>
          <div className="topbar-actions">
            <button
              className={currentPage === 'Notifications' ? 'notification-btn active' : 'notification-btn'}
              onClick={onOpenNotifications}
              aria-label={`Notifications${notificationCount > 0 ? `, ${notificationCount} need review` : ''}`}
              title="Notifications"
            >
              <Icon name="bell" size={19} />
              <span className="notification-label">Notifications</span>
              {notificationCount > 0 && <span className="notification-count">{notificationCount}</span>}
            </button>
            {user && (
              <button className="logout-btn" onClick={onLogout} aria-label={`Log out ${user.name}`}>
                <Icon name="logout" size={17} />
                <span>Log out</span>
              </button>
            )}
          </div>
        </header>
        <main className="main">{children}</main>

        <footer className="footer">
          <p>QubWatch — See what deserves your utmost attention.</p>
        </footer>
      </div>

      <MobileNav
        currentPage={currentPage}
        onNavigate={onNavigate}
        openAlertCount={notificationCount}
      />
    </div>
  )
}

export default Layout
